# Generated by Django 4.1.5 on 2023-01-22 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaposteo', models.DateField(blank=True)),
                ('titulo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
                ('imagenlibro', models.ImageField(upload_to='posteos')),
                ('sinopsis', models.CharField(max_length=2000)),
                ('imagenautor', models.ImageField(upload_to='posteos')),
                ('sobreautor', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=60)),
                ('genero', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avatars')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
